### ISSUE TITLE
Linking against OpenSSL when rustls is chosen

### ISSUE THREAD

**Issue by dpieczynski** [yoshidan/google-cloud-rust#133]
When using the following dependencies:
```toml
google-cloud-storage = {version = "0.10.0", default-features = false, features = ["rustls-tls"]}
google-cloud-default = {version = "0.1.1", default-features = false, features = ["storage", "rustls-tls"]}
```

the compiled binary still links against `libssl.so`.

I'm definitely not an expert in Rust, but it looks like this is caused by the lack of `default-features = false` [here](https://github.com/yoshidan/google-cloud-rust/blob/1366fe2830e2c6fb1513d3d420792b2c5d21ec1b/default/Cargo.toml#L24). I don't know if any other changes will be necessary.
